# -*- coding: utf-8 -*-
"""ML_group.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1b6JktKhJ2xs3ETw5qJWyh1mB4bp9Zg4n
"""

pip install yfinance



import numpy as np
import pandas as pd
import yfinance as yf


# to scrap the the stock data from yahoo finance 
def scrapStocks(stocklist,duration):
  for stock in stocklist:
    data_df=yf.download(stock,period=duration)
    data_df.to_csv(stock+'.csv')

# It will create the files for all the stocks
stocksName=['ADANIPOWER.NS','TATAPOWER.NS','RPOWER.NS','JKCEMENT.NS','AMBUJACEM.NS','ACC.NS']
scrapStocks(stocksName,"90d")

import pandas as pd 
import numpy as np 
from sklearn.linear_model import LinearRegression  
import matplotlib.pyplot as plt 
from sklearn.metrics import mean_squared_error, mean_absolute_error, mean_absolute_percentage_error,r2_score


# Reading the consolidated file of stocks
df= pd.read_csv('stockData.csv')

"""# New Section"""

# droping the null values
df=df.dropna()

# with six input features
data = df[['OPEN','LOW','CLOSE','NO. OF SHARES', 'NO. OF TRADES', 'Tata powers']]
output =df[['HIGH']]

print(len(data))
#Splitting between training and test 90,10 split

Xtrain= data[: int(0.9*len(data))]
Ytrain= output[: int(0.9*len(data))]
Xtest1=data[int(0.9*len(data)) :]
Ytest= output[int(0.9*len(data)):]

model1 = LinearRegression()
model1.fit(Xtrain,Ytrain)
model1.coef_


# calculating Mean Squared Error 
print('MSE test %.3f' % (mean_squared_error(model1.predict(Xtest1), Ytest)))
# calculating R-Squared
print('R^2  test: %.3f' % (r2_score(model1.predict(Xtest1), Ytest)))
# calculating absolute error
print('MAE test: %.3f' % (mean_absolute_error(model1.predict(Xtest1), Ytest)))
# calculating absolute percentage error
print('MAPE test: %.3f' % (mean_absolute_percentage_error(model1.predict(Xtest1), Ytest)))

# adding new featires with rolling 3point and 5 point average

df['MVA3'] = df['OPEN'].shift(1).rolling(window=3).mean() 
df['MVA5']= df['OPEN'].shift(1).rolling(window=5).mean()

df=df.dropna()
df.head(10)

data = df[['OPEN','LOW','CLOSE','NO. OF SHARES', 'NO. OF TRADES', 'Tata powers','MVA3','MVA5']]
output =df[['HIGH']]

data

data
print(len(data))
#Splitting between training and test 90,10 split

Xtrain= data[: int(0.9*len(data))]
Ytrain= output[: int(0.9*len(data))]
Xtest=data[int(0.9*len(data)) :]
Ytest= output[int(0.9*len(data)):]

# training the Linear Regression model

model = LinearRegression()
model.fit(Xtrain,Ytrain)

model.coef_

# Error estimation with new features
# calculating Mean Squared Error 
print('MSE test %.3f' % (mean_squared_error(model.predict(Xtest), Ytest)))
# calculating R-Squared
print('R^2  test: %.3f' % (r2_score(model.predict(Xtest), Ytest)))
# calculating absolute error
print('MAE test: %.3f' % (mean_absolute_error(model.predict(Xtest), Ytest)))
# calculating absolute percentage error
print('MAE test: %.3f' % (mean_absolute_percentage_error(model.predict(Xtest), Ytest)))

#plotting the results

import matplotlib.pyplot as plt
plt.style.use('default')

plt.figure(figsize=(10, 5), dpi=100)
  
# using plot method to plot open prices.
# in plot method we set the label and color of the curve.
predicted_price = pd.DataFrame(zip(model.predict(Xtest),Ytest.iloc[:, 0]),date1,columns=['prediction','test'])
predicted_price['prediction']=predicted_price['prediction'].astype(float)
predicted_price['prediction'].plot(label='predicted price', color='Green')
predicted_price.test.plot(label='actual price',color='brown') 
# adding title to the plot
plt.ylabel('Stock price')
  
# adding Label to the x-axis  
# adding legend to the curve
plt.legend()

# training lasso regression
dictParm={}
dictIntercept={}
mean_error=[]; std_error=[]
Ci_range = [ 0.5, 1, 5, 10,70,90,100,150,200, 500]
from sklearn.linear_model import Lasso
for Ci in Ci_range:
  model3 = Lasso(alpha=1/(2*Ci))
  model3.fit(Xtrain,Ytrain)
  ypred = model3.predict(Xtest)
  print("Lasso Regression for C= "+str(Ci))
  print("Coefficient =" +str(model3.coef_))
  print("Theta0 =" +str(model3.intercept_))
  mean_error.append(mean_squared_error(model3.predict(Xtest),Ytest))
  param=model3.coef_
  dictParm[Ci]=param
  dictIntercept[Ci]=model3.intercept_

import matplotlib.pyplot as plt
plt.style.use('default')

plt.figure(figsize=(10, 5), dpi=100)
plt.plot(Ci_range,mean_error,'-')
plt.xlabel('Ci values')
plt.ylabel('Mean square error')
plt.show()

# selecting the best value from above calculation
Ci=70
model3 = Lasso(alpha=1/(2*Ci))
model3.fit(Xtrain,Ytrain)
ypred = model.predict(Xtest)

# calculating Mean Squared Error with new features
print('MSE test %.3f' % (mean_squared_error(model3.predict(Xtest), Ytest)))
# calculating R-Squared
print('R^2  test: %.3f' % (r2_score(model3.predict(Xtest), Ytest)))
# calculating absolute error
print('MAE test: %.3f' % (mean_absolute_error(model3.predict(Xtest), Ytest)))
# calculating absolute percentage error
print('MAE test: %.3f' % (mean_absolute_percentage_error(model3.predict(Xtest), Ytest)))

import matplotlib.pyplot as plt
plt.style.use('default')

plt.figure(figsize=(10, 5), dpi=100)
  
# using plot method to plot open prices.
# in plot method we set the label and color of the curve.
predicted_price = pd.DataFrame(zip(model3.predict(Xtest),Ytest.iloc[:, 0]),date1,columns=['prediction','test'])
predicted_price['prediction']=predicted_price['prediction'].astype(float)
predicted_price.prediction.plot(label='predicted price', color='orange')
predicted_price.test.plot(label='actual price',color='blue') 
# adding title to the plot
plt.ylabel('Stock price')
  
# adding Label to the x-axis  
# adding legend to the curve
plt.legend()

# training the support vector regression model

from sklearn.svm import SVR
model2 = SVR(kernel = 'rbf')
model2.fit(Xtrain, Ytrain.values.ravel())

# calculating Mean Squared Error with new features
print('MSE test %.3f' % (mean_squared_error(model2.predict(Xtest), Ytest)))
# calculating R-Squared
print('R^2  test: %.3f' % (r2_score(model2.predict(Xtest), Ytest)))
# calculating absolute error
print('MAE test: %.3f' % (mean_absolute_error(model2.predict(Xtest), Ytest)))
# calculating absolute percentage error
print('MAE test: %.3f' % (mean_absolute_percentage_error(model2.predict(Xtest), Ytest)))

# plotting
import matplotlib.pyplot as plt
plt.style.use('default')

plt.figure(figsize=(10, 5), dpi=100)
  
# using plot method to plot open prices.
# in plot method we set the label and color of the curve.
predicted_price = pd.DataFrame(zip(model2.predict(Xtest),Ytest.iloc[:, 0]),date1,columns=['prediction','test'])
predicted_price['prediction']=predicted_price['prediction'].astype(float)
predicted_price.prediction.plot(label='predicted price', color='orange')
predicted_price.test.plot(label='actual price',color='blue') 
# adding title to the plot
plt.ylabel('Stock price')
  
# adding Label to the x-axis  
# adding legend to the curve
plt.legend()

# plotting all the results in same graph

plt.figure(figsize=(10, 5), dpi=100)
  
# using plot method to plot open prices.
# in plot method we set the label and color of the curve.
predicted_price1 = pd.DataFrame(zip(model1.predict(Xtest1),Ytest.iloc[:, 0]),date1,columns=['prediction','test'])
predicted_price2 = pd.DataFrame(zip(model.predict(Xtest),Ytest.iloc[:, 0]),date1,columns=['prediction','test'])
predicted_price3 = pd.DataFrame(zip(model3.predict(Xtest),Ytest.iloc[:, 0]),date1,columns=['prediction','test'])
predicted_price4 = pd.DataFrame(zip(model2.predict(Xtest),Ytest.iloc[:, 0]),date1,columns=['prediction','test'])

predicted_price1['prediction']=predicted_price1['prediction'].astype(float)
predicted_price2['prediction']=predicted_price2['prediction'].astype(float)
predicted_price3['prediction']=predicted_price3['prediction'].astype(float)
predicted_price4['prediction']=predicted_price4['prediction'].astype(float)

predicted_price1.prediction.plot(label='Linear Regression', color='orange')
predicted_price2.prediction.plot(label='LR with New feat.',color='red')
predicted_price3.prediction.plot(label='Lasso Regression',color='green')
#predicted_price4.prediction.plot(label='Support Vector Regression')
predicted_price.test.plot(label='actual price',color='blue') 
# adding title to the plot
plt.ylabel('Stock price')
  
# adding Label to the x-axis  
# adding legend to the curve
plt.legend()

stockprofile = []
stocksName=['ADANIPOWER.NS','TATAPOWER.NS','RPOWER.NS','JKCEMENT.NS','AMBUJACEM.NS','ACC.NS']
for stock in stocksName:
  info=[]
  ticker = yf.Ticker(stock)
  info.append(stock)
  info.append(ticker.info['industry'])
  info.append(ticker.info['totalRevenue'])
  info.append(ticker.info['volume'])
  info.append(ticker.info['sector'])
  stockprofile.append(info)
df1 = pd.DataFrame(stockprofile, columns = ['Name','industry','totalRevenue','volume','sector'])
df1.to_csv('StockInfo.csv')

df1

df1['industry']=df1['industry'].map({'Utilities—Independent Power Producers':'1', 'Utilities—Renewable':'2', 'Building Materials': '3'})
df1['sector']=df1['sector'].map({'Utilities':'1','Basic Materials':'2'})

df1

from sklearn import svm
model4 = svm.SVC()
X =df1[['totalRevenue','volume','sector']][1:]
y=df1[['industry']][1:]
xtest =df1[['totalRevenue','volume','sector']][:1]

model4.fit(X,y.values.ravel())

model4.predict(xtest)